caddy_base_config: |
  {
      email admin@solis-system.com
      log {
        output stdout
        format console
      }
  }

services:
  Lolapp:
    solisws_api:
      title: "Solisws API"
      description: "Bakend API Laravel"
      icon: mdi-api
      image: ${REGISTRY_URL}/api:latest
      dev_path: ../backend_lolapp
      subdomain: api
      internal_port: 8000

    solisws_pwa:
      title: "Solisws PWA"
      description: "VueJS application"
      icon: mdi-application-outline
      image: ${REGISTRY_URL}/app:latest
      subdomain: "master-*"
#    lolafrance_api:
#      title: "LolaFrance API"
#      description: "Backend API Laravel"
#      icon: mdi-api
#      image: ${REGISTRY_URL}/api:latest
#      subdomain: beta.api
#      internal_port: 8000
#
#    lolafrance_pwa:
#      title: "LolaFrance PWA"
#      description: "VueJS application"
#      icon: mdi-application-outline
#      image: ${REGISTRY_URL}/app:latest
#      subdomain: "*.beta"
#      internal_port: 80

    webdev-a:
      title: "Serveur Application"
      description: "Webdev 28"
      icon: mdi-server-minus
      image: windev/webdev:FR280094s
      subdomain: ws-a
      storage: internal
      volumes:
        - webdev-a_data:/var/lib/WEBDEV/28.0/
      environment:
        - NUMERO_DE_SERIE
        - CLE_D_ACTIVATION
        - TZ
      command: --configuration=${NUMERO_DE_SERIE}-${CLE_D_ACTIVATION}
  Outils:
    homepage:
      title: "Home"
      description: ""
      icon: mdi-home-account
      image: ghcr.io/gethomepage/homepage
      subdomain:
      internal_port: 3000
      volumes:
        - ./config/homepage:/app/config
        - /var/run/docker.sock:/var/run/docker.sock

    mailpit:
      title: "Mailpit"
      description: "Serveur mail de test"
      icon: mdi-email-outline
      image: axllent/mailpit
      subdomain: mailpit
      internal_port: 8025
      environment:
        - TZ
      storage: internal
      volumes:
        - mailpit_data:/data

    registry-ui:
      title: "Registry UI"
      description: "Interface web image docker"
      icon: mdi-image
      image: joxit/docker-registry-ui:latest
      subdomain: registry
      environment:
        - REGISTRY_TITLE
        - NGINX_PROXY_PASS_URL
        - DELETE_IMAGES
        - SINGLE_REGISTRY
    pma:
      image: phpmyadmin:5.2.1-apache
      title: "PHPMyAdmin"
      description: "SQL Viewer"
      icon: mdi-database-search
      subdomain: pma
      depends_on:
        - mariadb
    n8n:
      image: n8nio/n8n:latest
      title: "n8n"
      description: "Automatisation Workflow"
      icon: mdi-home-automation
      subdomain: n8n
      internal_port: 5678
      storage: internal
      volumes:
        - n8n_data:/home/node/.n8n
    uptime:
      image: louislam/uptime-kuma:1.23.8
      title: "Uptime Kuma"
      description: "Monitoring service"
      icon: mdi-radar
      subdomain: uptime
      internal_port: 3001
      storage: internal
      volumes:
        - uptime_data:/app/data
        - /var/run/docker.sock:/var/run/docker.sock
  Data:
    minio:
      title: "Minio"
      description: "S3 Storage"
      icon: mdi-nas
      image: quay.io/minio/minio
      subdomain: minio
      internal_port: 9090
      storage:
      volumes:
        - minio_data:/data
      environment:
        - MINIO_ROOT_USER
        - MINIO_ROOT_PASSWORD
      command: server /data --console-address :9090

    registry:
      title: "Docker Registry"
      description: "Stockage d'image docker private"
      icon: mdi-docker
      image: registry:latest
      storage: external
      environment:
        - BASIC_AUTH
      volumes:
        - registry_data:/var/lib/registry

    redis:
      title: "Redis"
      description: "Cache"
      icon: mdi-database-cog-outline
      image: redis/redis-stack
      storage: internal
      volumes:
        - redis_data:/data

    mariadb:
      title: "Mysql"
      description: "Base de donnes"
      icon: mdi-database
      image: mariadb:11.0.2
      storage:
      volumes:
        - mariadb_data:/var/lib/mysql
      environment:
        - MARIADB_PASSWORD
        - MARIADB_USER
        - MARIADB_ROOT_PASSWORD

    hfsql:
      title: "HSQL"
      description: "Base de donnes"
      icon: mdi-database
      image: windev/hfsql:FR280085e
      storage: internal
      volumes:
        - hfsql_data:/var/lib/hfsql
      environment:
        - HFSQL_RANDOM_PASSWORD
        - HFSQL_USER
      ports:
        - 4900:4900

