services:
  api:
    group: 1
    title: "Solisws API"
    description: "Backend API Laravel"
    icon: mdi-api
    image: ${REGISTRY_URL}/api:latest
    dev_path: ../../api
    subdomain: api
    internal_port: 8000

  pwa:
    group: 1
    title: "Solisws PWA"
    description: "VueJS application"
    icon: mdi-application-outline
    image: ${REGISTRY_URL}/app:latest
    dev_path: ../../lolapp
    subdomain: "*"
    internal_port: 8085

  nocodb:
    group: 1
    title: "NocoDB"
    description: "Base de donnee"
    icon: mdi-database-settings
    image: nocodb/nocodb:latest
    subdomain: nocodb
    internal_port: 8080

  webdev-a:
    group: 1
    title: "Serveur Application"
    description: "Webdev 28"
    icon: mdi-server-minus
    image: windev/webdev:FR280094s
    subdomain: ws-a
    storage: internal
    volumes:
      - webdev-a_data:/var/lib/WEBDEV/28.0/
    environment:
      - NUMERO_DE_SERIE
      - CLE_D_ACTIVATION
      - TZ
    command: --configuration=${NUMERO_DE_SERIE}-${CLE_D_ACTIVATION}

  homepage:
    group: 2
    title: "Home"
    description: ""
    icon: mdi-home-account
    image: ghcr.io/gethomepage/homepage
    subdomain:
    internal_port: 3000
    volumes:
      - ../conf/homepage:/app/config
      - ./homepage_services.yaml:/app/config/services.yaml
      - /var/run/docker.sock:/var/run/docker.sock

  watchtower:
    group: 2
    title: "Watchtower"
    description: "Mise a jour automatique des images"
    icon: mdi-radar
    image: containrrr/watchtower
    command: >
      --interval 300
      --notification-url mattermost://mattermost.solisws.fr/j88b7ik1zbnt58twb4hatjaa9o
      --notification-template "({{.Level}})"
      --notification-report
    volumes:
      - ~/.docker/config.json:/config.json
      - /var/run/docker.sock:/var/run/docker.sock
  mailpit:
    group: 2
    title: "Mailpit"
    description: "Serveur mail de test"
    icon: mdi-email-outline
    image: axllent/mailpit
    subdomain: mailpit
    internal_port: 8025
    environment:
      - TZ
    storage: internal
    volumes:
      - mailpit_data:/data

  registry-ui:
    group: 2
    title: "Registry UI"
    description: "Interface web image docker"
    icon: mdi-image
    image: joxit/docker-registry-ui:latest
    subdomain: registry
    auth: basic
    environment:
      - REGISTRY_TITLE
      - NGINX_PROXY_PASS_URL
      - DELETE_IMAGES
      - SINGLE_REGISTRY

  pma:
    group: 2
    title: "PHPMyAdmin"
    description: "SQL Viewer"
    icon: mdi-database-search
    image: phpmyadmin:5.2.1-apache
    subdomain: pma
    depends_on:
      - mariadb

  n8n:
    group: 2
    image: n8nio/n8n:latest
    title: "n8n"
    description: "Automatisation Workflow"
    icon: mdi-home-automation
    subdomain: n8n
    internal_port: 5678
    storage: internal
    volumes:
      - n8n_data:/home/node/.n8n

  uptime:
    group: 2
    image: louislam/uptime-kuma:1.23.8
    title: "Uptime Kuma"
    description: "Monitoring service"
    icon: mdi-radar
    subdomain: uptime
    internal_port: 3001
    storage: internal
    volumes:
      - uptime_data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock

  minio:
    group: 3
    title: "Minio"
    description: "S3 Storage"
    icon: mdi-nas
    image: quay.io/minio/minio
    subdomain: minio
    internal_port: 9090
    storage: external
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER
      - MINIO_ROOT_PASSWORD
    command: server /data --console-address :9090

  registry:
    group: 3
    title: "Docker Registry"
    description: "Stockage d'image docker private"
    icon: mdi-docker
    image: registry:latest
    storage: external
    auth: basic
    environment:
      - BASIC_AUTH
    volumes:
      - registry_data:/var/lib/registry

  redis:
    group: 3
    title: "Redis"
    description: "Cache"
    icon: mdi-database-cog-outline
    image: redis/redis-stack
    storage: internal
    volumes:
      - redis_data:/data

  mariadb:
    group: 3
    title: "Mysql"
    description: "Base de donnes"
    icon: mdi-database
    image: mariadb:11.0.2
    storage: external
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      - MARIADB_PASSWORD
      - MARIADB_USER
      - MARIADB_ROOT_PASSWORD

  hfsql:
    group: 3
    title: "HSQL"
    description: "Base de donnes"
    icon: mdi-database
    image: windev/hfsql:FR280085e
    storage: internal
    volumes:
      - hfsql_data:/var/lib/hfsql
    environment:
      - HFSQL_RANDOM_PASSWORD
      - HFSQL_USER
    ports:
      - 4900:4900

