services:
  minio:
    container_name: minio
    image: quay.io/minio/minio
    restart: always
    env_file:
      - .env
    environment:
      MINIO_SERVER_URL: https://api-minio.lola-france.fr
      MINIO_BROWSER_REDIRECT_URL: https://minio.lola-france.fr
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://127.0.0.1:9000/minio/health/live"
        ]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - minio-data:/data
    networks:
      - proxy-network
    command: server /data --console-address :9090

volumes:
  minio-data:


networks:
  proxy-network:
    external: true
