services:
  caddy:
    container_name: caddy
    image: caddy:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
      - "5000:5000"
    restart: always
    networks:
      - proxy-network