services:
  registry:
    container_name: registry
    image: registry:latest
    networks:
      - proxy-network
    volumes:
      - registry-data:/var/lib/registry

  registry-ui:
    container_name: registry_ui
    image: joxit/docker-registry-ui:latest
    restart: always
    environment:
      REGISTRY_TITLE: "Solis Registry"
      NGINX_PROXY_PASS_URL: "http://registry:5000"
      DELETE_IMAGES: true
      SINGLE_REGISTRY: true
    depends_on:
      - registry
    networks:
      - proxy-network

volumes:
  registry-data:


networks:
  proxy-network:
    external: true
