services:
  registry:
    container_name: registry-server
    image: registry:latest
    networks:
      - proxy-network

  registry-ui:
    container_name: registry-ui
    image: joxit/docker-registry-ui:latest
    restart: always
    environment:
      REGISTRY_TITLE: "Solis Registry"
      NGINX_PROXY_PASS_URL: "http://registry-server:5000"
      DELETE_IMAGES: true
      SINGLE_REGISTRY: true
    depends_on:
      - registry
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true
