- Lolapp:
  - Solisws API:
      href: http://api.localhost
      container: solisws_api
      showStats: true
      description: Bakend API Laravel
      icon: mdi-api
  - Solisws PWA:
      href: http://solisws_pwa.localhost
      container: solisws_pwa
      showStats: true
      description: VueJS application
      icon: mdi-application-outline
  - LolaFrance API:
      href: http://beta.api.localhost
      container: lolafrance_api
      showStats: true
      description: Backend API Laravel
      icon: mdi-api
  - LolaFrance PWA:
      href: http://beta.localhost
      container: lolafrance_pwa
      showStats: true
      description: VueJS application
      icon: mdi-application-outline
  - Serveur Application:
      href: http://ws-a.localhost
      container: webdev-a
      showStats: true
      description: Webdev 28
      icon: mdi-server-minus
- Outils:
  - Home:
      href: http://localhost
      container: homepage
      showStats: true
      description: ''
      icon: mdi-home-account
  - Mailpit:
      href: http://mailpit.localhost
      container: mailpit
      showStats: true
      description: Serveur mail de test
      icon: mdi-email-outline
  - Registry UI:
      href: http://registry.localhost
      container: registry-ui
      showStats: true
      description: Interface web image docker
      icon: mdi-image
  - PHPMyAdmin:
      href: http://pma.localhost
      container: pma
      showStats: true
      description: SQL Viewer
      icon: mdi-database-search
  - n8n:
      href: http://n8n.localhost
      container: n8n
      showStats: true
      description: Automatisation Workflow
      icon: mdi-home-automation
  - Uptime Kuma:
      href: http://uptime.localhost
      container: uptime
      showStats: true
      description: Monitoring service
      icon: mdi-radar
- Services:
  - Caddy:
      href: '#'
      container: caddy
      showStats: true
      description: Reverse Proxy
      icon: mdi-arrow-decision
  - Minio:
      href: http://minio.localhost
      container: minio
      showStats: true
      description: S3 Storage
      icon: mdi-nas
  - Docker Registry:
      href: '#'
      container: registry
      showStats: true
      description: Stockage d'image docker private
      icon: mdi-docker
  - Redis:
      href: '#'
      container: redis
      showStats: true
      description: Cache
      icon: mdi-database-cog-outline
  - Mysql:
      href: '#'
      container: mariadb
      showStats: true
      description: Base de donnes
      icon: mdi-database
  - HSQL:
      href: '#'
      container: hfsql
      showStats: true
      description: Base de donnes
      icon: mdi-database
