---
title: Solis System Server
showStats: true
language: fr
hideVersion: true
statusStyle: "basic"
headerStyle: clean
theme: dark
color: green
#background: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80

quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  showSearchSuggestions: true
  hideVisitURL: true
  provider: google